### ISSUE TITLE
TODO v1.0

### ISSUE THREAD

**Issue by flaxues** [NetherKingdom/EnderAuth#2]
#### TODO (v1.0.0):
- [x] Messages
- [ ] Email system
- [x] Change password
- [x] Login - register commands etc.
- [x] No moving (event)
- [x] Only chat after logged in (event)
- [x] Only allowed commands when not logged in: /login, /register, /help
- [x] login timeout after 5 minutes

**Comment by matthew4444** [comment]
Hey look at readme.md

**Comment by matthew4444** [comment]
Look at readme

**Comment by matthew4444** [comment]
Hey

**Comment by matthew4444** [comment]
hey

**Comment by matthew4444** [comment]
Hellllooooooo r u on?

**Comment by matthew4444** [comment]
HELLLOOOO

**Comment by matthew4444** [comment]
Hellooooo

**Comment by matthew4444** [comment]
Hello

**Comment by matthew4444** [comment]
Hi

**Comment by matthew4444** [comment]
Hi

**Comment by flaxues** [comment]
I don't think a email system is gonna work because for that you need a email server!

**Comment by matthew4444** [comment]
Ok,then lets take it out

**Comment by matthew4444** [comment]
And what took u so long to respond

**Comment by matthew4444** [comment]
Hello

**Comment by flaxues** [comment]
I had dinner

**Comment by matthew4444** [comment]
Hello r u afk

**Comment by matthew4444** [comment]
Hello

**Comment by matthew4444** [comment]
Ok

**Comment by Driesboy** [comment]
Upload sources please

**Comment by matthew4444** [comment]
Flazus
Did u put ur code in

**Comment by matthew4444** [comment]
Falxues were alsmodt done with plugun -.-

**Comment by flaxues** [comment]
```
[20:44:58] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'EnderAuth v1.0.0': Call to undefined method EnderAuth\EnderAuth\LoginAndRegister::isOp() on EnderAuth\EnderAuth\LoginAndRegister
[20:44:58] [Server thread/CRITICAL]: Error: "Call to undefined method EnderAuth\EnderAuth\LoginAndRegister::isOp()" (EXCEPTION) in "/plugins/EnderAuth/src/EnderAuth/EnderAuth/LoginAndRegister" at line 28

```

I can't fix this...

**Comment by matthew4444** [comment]
Hey
Go here

> 
https://gitter.im/matthew4444/NetherKingdom
